name: WANDER + ECHO
favicon: null
layout_spectrum: 0.76044
typography_spectrum: 0.29390353872440755
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5
  lightness: 0.06766264303587377
  saturation: 0.35314267850480974
  rhythmicContrast: 0.7528462135232985
purpose: []
